1. Please use broadcasting or other methods to speed up the following simulation codes. You need to roughly speed it up 5 times as the minimum requirement. (Without speedup, the time used in my computer is 137 seconds, and the improved code uses only 27 seconds.)

2. Similar to `range()`, define a custom function `arange()` that can also accept floating point numbers with optional arguments (start, stop, step) and return a list that contains a sequence of numbers from start (inclusive) to stop (exclusive) by step. Do not use `numpy.arange()` for practicing. The function can automatically change the default step from 1 to -1 when implied. The user will repeatedly input the function to evaluate (quit upon error). Your output should look like this:


    Enter an expression with arange(): arange(stop=0)
    []
    Enter an expression with arange(): arange(stop=5)
    [0, 1, 2, 3, 4]
    Enter an expression with arange(): arange(stop=-5)
    [0, -1, -2, -3, -4]
    Enter an expression with arange(): arange(stop=5.1)
    [0.0, 1.0, 2.0, 3.0, 4.0, 5.0]
    Enter an expression with arange(): arange(-1.1,1.1)
    [-1.1, -0.1, 0.9]
    Enter an expression with arange(): arange(1.1,-1.1)
    [1.1, 0.1, -0.9]
    Enter an expression with arange(): arange(-1,1,0.9)
    [-1.0, -0.1, 0.8]
    Enter an expression with arange(): arange(1,-1,-1/3)
    [1.0, 0.6666666666666666, 0.3333333333333333, 0.0, -0.3333333333333333, -0.6666666666666666]
    Enter an expression with arange(): [i*2 for i in arange(1,2,0.2)]
    [2.0, 2.4, 2.8, 3.2, 3.6]
    Enter an expression with arange(): 

3. An identity matrix is defined as a square matrix with 1s running from the top left of the square to the bottom right and the rest are 0s. Create a numpy.ndarray that takes an integer n and print the identity matrix of n x n dimensions. For this question, if the integer is negative, return the mirror image of the identity matrix of n x n dimensions. It does not matter if the mirror image is left-right or top-bottom. Incompatible types passed as n should return the string "Error". Your output should look like one of these:


    Enter dimension of identity matrix: 0
    []
***
    Enter dimension of identity matrix: 2
    [[1 0]
     [0 1]]
***
    Enter dimension of identity matrix: -2
    [[0 1]
     [1 0]]

4. Create a 3x3 matrix of a tic-tac-toe game as numpy.ndarray called `TicTacToe` and print it out for every turn. All the matrix elements are zeros (0) at first and then filled randomly in position by one (1) first and then two (2) alternatively. The game ends and display "1 wins" or "2 wins" when either side wins the game or "Draw" when completely filled without a winner. Your output should look like this:


    [[0 0 0]
     [0 0 0]
     [0 0 0]]
    After turn 1:
    [[0 0 0]
     [0 0 0]
     [1 0 0]]
    After turn 2:
    [[0 0 0]
     [0 2 0]
     [1 0 0]]
    After turn 3:
    [[0 1 0]
     [0 2 0]
     [1 0 0]]
    After turn 4:
    [[0 1 0]
     [2 2 0]
     [1 0 0]]
    After turn 5:
    [[1 1 0]
     [2 2 0]
     [1 0 0]]
    After turn 6:
    [[1 1 0]
     [2 2 2]
     [1 0 0]]
    2 wins

5. Now add some AI to question 4 to override choosing a place randomly for each turn in the tic-tac-toe game. First, see if there is a place to take that will win the game. If there is, take that place. Otherwise, see if there is a place the other side can take that will win the game. If there is, take there to block the other side. Otherwise, continue with the randomly selected place remaining. Run the simulation until 1 second is reached. Your output should look like this:


    Probability of 1 wins: 
    Probability of 2 wins: 
    Probability of draw: 
    Games completed: 
    Simulation time: 

6. A cereal company is giving away a prize in each box of cereal and they advertise "Collect all 10 prizes!". Each box of cereal has 1 prize, and each prize is equally likely to appear in any given box. Estimate how many boxes it takes, on average, to get N different prizes using simulation for just 0.1 second for each N. Your output should look like this:


    Total simulation time:
    
    N    Average boxes    
    1    1.0
    2