1. Please use broadcasting or other methods to speed up the following simulation codes. You need to roughly speed it up 5 times as the minimum requirement. (Without speedup, the time used in my computer is 137 seconds, and the improved code uses only 27 seconds.)

In [1]:
import numpy as np
import time

#only one bullet in the gun
num_test=20000000
num_pos=20
pos_take=tuple(range(10))

start_time=time.time()
np.random.seed(10)
num_lose=0
for nt in range(num_test):
    A=np.zeros(num_pos)
    A[np.random.randint(0,num_pos)]=1

    for n in range(num_pos):
        if A[n]==1:
            if n in pos_take:
                num_lose += 1
            break

print("The lose probability is:", num_lose/num_test)
print("Time:",time.time()-start_time)
print("Number of tests:",num_test)

The lose probability is: 0.4998927
Time: 189.76390027999878
Number of tests: 20000000


In [2]:
# Q1 answer
import numpy as np
import time

#only one bullet in the gun
num_test=20000000
num_pos=20
pos_take=tuple(range(10))

start_time=time.time()
np.random.seed(10)
num_lose=0

#B is an array storing the bullet position of each test
B=np.random.randint(0,20,num_test)

for n in pos_take:
    num_lose+= (B==n).sum()

print("The lose probability is:", num_lose/num_test)
print("Time:",time.time()-start_time)
print("Number of tests:",num_test)

The lose probability is: 0.4998927
Time: 0.8485164642333984
Number of tests: 20000000


2. Similar to `range()`, define a custom function `arange()` that can also accept floating point numbers with optional arguments (start, stop, step) and return a list that contains a sequence of numbers from start (inclusive) to stop (exclusive) by step. Do not use `numpy.arange()` for practicing. The function can automatically change the default step from 1 to -1 when implied. The user will repeatedly input the function to evaluate (quit upon error). Your output should look like this:


    Enter an expression with arange(): arange(stop=0)
    []
    Enter an expression with arange(): arange(stop=5)
    [0, 1, 2, 3, 4]
    Enter an expression with arange(): arange(stop=-5)
    [0, -1, -2, -3, -4]
    Enter an expression with arange(): arange(stop=5.1)
    [0.0, 1.0, 2.0, 3.0, 4.0, 5.0]
    Enter an expression with arange(): arange(-1.1,1.1)
    [-1.1, -0.1, 0.9]
    Enter an expression with arange(): arange(1.1,-1.1)
    [1.1, 0.1, -0.9]
    Enter an expression with arange(): arange(-1,1,0.9)
    [-1.0, -0.1, 0.8]
    Enter an expression with arange(): arange(1,-1,-1/3)
    [1.0, 0.6666666666666666, 0.3333333333333333, 0.0, -0.3333333333333333, -0.6666666666666666]
    Enter an expression with arange(): [i*2 for i in arange(1,2,0.2)]
    [2.0, 2.4, 2.8, 3.2, 3.6]
    Enter an expression with arange(): 

In [3]:
# Q2 answer
import math

def decimal_length(x):
    max_decimals = 16
    int_part = int(abs(x))
    frac_part = abs(x) - int_part
    multiplier = 10 ** max_decimals
    frac_digits = multiplier + int(multiplier * frac_part)
    while frac_digits % 10 == 0:
        frac_digits /= 10
    scale = int(math.log10(frac_digits))
    return scale 

def arange(start=0,stop=0,step=1):
    e = 1e-15
    target=[]
    if type(start)==float or type(stop)==float or type(step)==float:
        start = float(start)
        stop = float(stop)
        step = float(step)
        precision = max(decimal_length(start),decimal_length(stop),decimal_length(step))
        while start < stop - e:
            target.append(start)
            start = round(start + step,precision)
            if abs(start-int(start)) <e:
                start = float(int(start))
        if target==[]:
            if step > 0:
                step = -step
            while start > stop + e:
                target.append(start)
                start = round(start + step,precision)
                if abs(start-int(start)) <e:
                    start = float(int(start))
    else:
        while start < stop:
            target.append(start)
            start += step
        if target==[]:
            if step > 0:
                step = -step
            while start > stop:
                target.append(start)
                start += step
    return target

while True:
    a = input('Enter an expression with arange(): ')
    try:
        print(eval(a))
    except:
        break

Enter an expression with arange(): arange(stop=0)
[]
Enter an expression with arange(): arange(stop=5)
[0, 1, 2, 3, 4]
Enter an expression with arange(): arange(stop=-5)
[0, -1, -2, -3, -4]
Enter an expression with arange(): arange(stop=5.1)
[0.0, 1.0, 2.0, 3.0, 4.0, 5.0]
Enter an expression with arange(): arange(-1.1,1.1)
[-1.1, -0.1, 0.9]
Enter an expression with arange(): arange(1.1,-1.1)
[1.1, 0.1, -0.9]
Enter an expression with arange(): arange(-1,1,0.9)
[-1.0, -0.1, 0.8]
Enter an expression with arange(): arange(1,-1,-1/3)
[1.0, 0.6666666666666667, 0.3333333333333334, 0.0, -0.3333333333333333, -0.6666666666666666]
Enter an expression with arange(): [i*2 for i in arange(1,2,0.2)]
[2.0, 2.4, 2.8, 3.2, 3.6]
Enter an expression with arange(): 


3. An identity matrix is defined as a square matrix with 1s running from the top left of the square to the bottom right and the rest are 0s. Create a numpy.ndarray that takes an integer n and print the identity matrix of n x n dimensions. For this question, if the integer is negative, return the mirror image of the identity matrix of n x n dimensions. It does not matter if the mirror image is left-right or top-bottom. Incompatible types passed as n should return the string "Error". Your output should look like one of these:


    Enter dimension of identity matrix: 0
    []
***
    Enter dimension of identity matrix: 2
    [[1 0]
     [0 1]]
***
    Enter dimension of identity matrix: -2
    [[0 1]
     [1 0]]

In [7]:
# Q3 answer
def identity(n):
    mirror = False
    if n<0:
        mirror = True
        n = -n
    matrix = np.zeros((n,n),int)
    if not mirror:
        one_position = 0
        r = 0
        while n>0:
            matrix[r,one_position]=1
            one_position += 1
            r += 1
            n -= 1
    else:
        one_position = n-1
        r = 0
        while n>0:
            matrix[r,one_position]=1
            one_position -= 1
            r += 1
            n -= 1
    return print(matrix)
    
n = input('Enter dimension of identity matrix: ')
try:
    identity(int(n))
except:
    print('Error')

Enter dimension of identity matrix: 
Error


4. Create a 3x3 matrix of a tic-tac-toe game as numpy.ndarray called `TicTacToe` and print it out for every turn. All the matrix elements are zeros (0) at first and then filled randomly in position by one (1) first and then two (2) alternatively. The game ends and display "1 wins" or "2 wins" when either side wins the game or "Draw" when completely filled without a winner. Your output should look like this:


    [[0 0 0]
     [0 0 0]
     [0 0 0]]
    After turn 1:
    [[0 0 0]
     [0 0 0]
     [1 0 0]]
    After turn 2:
    [[0 0 0]
     [0 2 0]
     [1 0 0]]
    After turn 3:
    [[0 1 0]
     [0 2 0]
     [1 0 0]]
    After turn 4:
    [[0 1 0]
     [2 2 0]
     [1 0 0]]
    After turn 5:
    [[1 1 0]
     [2 2 0]
     [1 0 0]]
    After turn 6:
    [[1 1 0]
     [2 2 2]
     [1 0 0]]
    2 wins

In [8]:
# Q4 answer
import numpy as np
def check_end(ttt):
    end = False
    for i in range(3):
        if ttt[i,0] == ttt[i,1] and ttt[i,1] == ttt[i,2] and ttt[i,0]!=0:
            return True, '{} wins'.format(ttt[i,0])
        if ttt[0,i] == ttt[1,i] and ttt[1,i] == ttt[2,i] and ttt[0,i]!=0:
            return True, '{} wins'.format(ttt[0,i])
    if ttt[0,0] == ttt[1,1] and ttt[1,1] == ttt[2,2] and ttt[0,0]!=0:
        return True, '{} wins'.format(ttt[0,0])
    if ttt[0,2] == ttt[1,1] and ttt[1,1] == ttt[2,0] and ttt[1,1]!=0:
        return True, '{} wins'.format(ttt[1,1])
    if (ttt==0).sum() == 0:
        return True, 'Draw'
    return False, None

TicTacToe = np.zeros((3,3),int)
end = False
player = ['',1,2]
ap = 1
turn = 1
print(TicTacToe)
while not end:
    p_i = np.random.randint(0,3)
    p_j = np.random.randint(0,3)
    while TicTacToe[p_i,p_j] != 0:
        p_i = np.random.randint(0,3)
        p_j = np.random.randint(0,3)
    TicTacToe[p_i,p_j] = player[ap]
    print('After turn {}:'.format(turn))
    print(TicTacToe)
    end, result = check_end(TicTacToe)
    if end:
        print(result)
    turn += 1
    ap = -ap
    

[[0 0 0]
 [0 0 0]
 [0 0 0]]
After turn 1:
[[0 0 0]
 [0 0 0]
 [0 1 0]]
After turn 2:
[[0 0 0]
 [2 0 0]
 [0 1 0]]
After turn 3:
[[0 0 1]
 [2 0 0]
 [0 1 0]]
After turn 4:
[[0 0 1]
 [2 0 0]
 [2 1 0]]
After turn 5:
[[0 1 1]
 [2 0 0]
 [2 1 0]]
After turn 6:
[[0 1 1]
 [2 0 2]
 [2 1 0]]
After turn 7:
[[0 1 1]
 [2 1 2]
 [2 1 0]]
1 wins


5. Now add some AI to question 4 to override choosing a place randomly for each turn in the tic-tac-toe game. First, see if there is a place to take that will win the game. If there is, take that place. Otherwise, see if there is a place the other side can take that will win the game. If there is, take there to block the other side. Otherwise, continue with the randomly selected place remaining. Run the simulation until 1 second is reached. Your output should look like this:


    Probability of 1 wins: 
    Probability of 2 wins: 
    Probability of draw: 
    Games completed: 
    Simulation time: 

In [9]:
# Q5 answer
def check_end(ttt):
    for i in range(3):
        if ttt[i,0] == ttt[i,1] and ttt[i,1] == ttt[i,2] and ttt[i,0]!=0:
            return True, ttt[i,0]
        if ttt[0,i] == ttt[1,i] and ttt[1,i] == ttt[2,i] and ttt[0,i]!=0:
            return True, ttt[0,i]
    if ttt[0,0] == ttt[1,1] and ttt[1,1] == ttt[2,2] and ttt[0,0]!=0:
        return True, ttt[0,0]
    if ttt[0,2] == ttt[1,1] and ttt[1,1] == ttt[2,0] and ttt[1,1]!=0:
        return True, ttt[1,1]
    if (ttt==0).sum() == 0:
        return True, 'Draw'
    return False, None

def check_win(ttt,player):
    for i in range(3):
        if (ttt[i,:]==player).sum()==2 and (ttt[i,:]==0).sum()==1:
            return True, (i,np.where(ttt[i,:]==0)[0][0])
        if (ttt[:,i]==player).sum()==2 and (ttt[:,i]==0).sum()==1:
            return True, (np.where(ttt[:,i]==0)[0][0],i)
    diagonal_1 = np.array([ttt[0,0],ttt[1,1],ttt[2,2]])
    diagonal_2 = np.array([ttt[0,2],ttt[1,1],ttt[2,0]])
    if (diagonal_1==player).sum()==2 and (diagonal_1==0).sum()==1:
        return True, (np.where(diagonal_1==0)[0][0],np.where(diagonal_1==0)[0][0])
    if (diagonal_2==player).sum()==2 and (diagonal_2==0).sum()==1:
        return True, (np.where(diagonal_2==0)[0][0],1-(np.where(diagonal_2==0)[0][0]-1))
    return False, None    
          
def TTT():
    TicTacToe = np.zeros((3,3),int)
    end = False
    player = ['',1,2]
    ap = 1
    turn = 1
    while not end and turn<=9:
        p_i = np.random.randint(0,3)
        p_j = np.random.randint(0,3)
        while TicTacToe[p_i,p_j] != 0:
            p_i = np.random.randint(0,3)
            p_j = np.random.randint(0,3)
        lose,p = check_win(TicTacToe,player[-ap])
        if lose:
            p_i = p[0]
            p_j = p[1]
        win,p = check_win(TicTacToe,player[ap])
        if win:
            p_i = p[0]
            p_j = p[1]
        TicTacToe[p_i,p_j] = player[ap]
        end, result = check_end(TicTacToe)
        if end:
            return result
        turn += 1
        ap = -ap
        
import time
games = 10000
tos = time.time()
results = {}
for i in range(games):
    r = TTT()
    if r not in results:
        results[r] = 1
    else:
        results[r]+=1

print('Probability of 1 wins: {}'.format(results[1]/games))
print('Probability of 2 wins: {}'.format(results[2]/games))
print('Probability of draw: {}'.format(results['Draw']/games))
print('Games completed: {}'.format(games))
print('Simulation time: {}s'.format(time.time()-tos))

Probability of 1 wins: 0.3077
Probability of 2 wins: 0.1817
Probability of draw: 0.5106
Games completed: 10000
Simulation time: 6.976471662521362s


6. A cereal company is giving away a prize in each box of cereal and they advertise "Collect all 10 prizes!". Each box of cereal has 1 prize, and each prize is equally likely to appear in any given box. Estimate how many boxes it takes, on average, to get N different prizes using simulation for just 0.1 second for each N. Your output should look like this:


    Total simulation time:
    
    N    Average boxes    
    1    1.0
    2

In [11]:
# Your Code Below
import numpy as np
import time 
import timeit

def estimate(N):
    n = 1
    while True:
        prizes = np.random.randint(1,N+1,n)
        distinct_prizes = len(np.unique(prizes))
        if distinct_prizes == N:
            break
        n+=1
    return n


simulation_count = 10000
result = np.zeros([10,simulation_count],int)
tos = time.time()
for i in range(10):
    for j in range(simulation_count):
        result[i,j]=estimate(i+1)
print('Total simulation time: {}s'.format(time.time()-tos))
means = result.mean(axis=1)
print()
print('N    Average boxes    Average Simulation Time')
for i in range(10):
    print('{:<5}{:<17.2f}{:.6f}s'.format(i+1,means[i],timeit.timeit('estimate({})'.format(i+1), globals=globals(), number=simulation_count)/simulation_count))


Total simulation time: 15.46067476272583s

N    Average boxes    Average Simulation Time
1    1.00             0.000015s
2    2.65             0.000041s
3    4.43             0.000068s
4    6.34             0.000097s
5    8.38             0.000130s
6    10.58            0.000164s
7    12.76            0.000198s
8    15.05            0.000244s
9    17.45            0.000274s
10   19.90            0.000316s
